# Generated by Django 2.2.6 on 2019-11-13 12:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('p_library', '0003_auto_20191113_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edition',
            new_name='Redaction',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='edition',
            new_name='redaction',
        ),
    ]
